### ISSUE TITLE
i get error in line

### ISSUE THREAD

**Issue by Ilolka1337** [xxDark/StringScrambler#1]
I am using Java 8 202
how can this be fixed?
![unknown](https://user-images.githubusercontent.com/63341162/88097063-491c0380-cba0-11ea-83fd-8a623d277b86.png)
![unknown (1)](https://user-images.githubusercontent.com/63341162/88097066-49b49a00-cba0-11ea-9a0b-a0d10b1822ff.png)

**Comment by xxDark** [comment]
See https://github.com/xxDark/StringScrambler/blob/master/transformer/src/main/java/me/xdark/stringscrambler/ScrambleTransformer.java
